### ISSUE TITLE
ENLP

### ISSUE THREAD

**Issue by vishchan85** [smartbgp/yabgp#103]
I have the following configuration for my BGP SR-TE udpate - 
{'attr': {'1': 0, '2': [[2, [100, 2]]], '14': {'nlri': {'color': 250, 'endpoint': '206.1.0', 'distinguisher': 6001}, 'afi_safi': [1, 73], 'nexthop': '47.8.1.1'}, '23': {'0': 'new', '13': 965540, '12': 4200, '128': [{'9': 10, '1': [{'1': {'label': 999980}}, {'1': {'label': 900003}}, {'1': {'label': 900002}}]}]}, '8': ['NO_ADVERTISE']}}

I was looking to add ENLP functionality described in https://tools.ietf.org/html/draft-ietf-idr-segment-routing-te-policy-07#section-2.4.4 What is the option to be used. The documentation at https://yabgp.readthedocs.io/en/latest/msg_format.html#ipv4-sr-policy doesn't mention about it.

**Comment by meidli** [comment]
@vishchan85 
Hi, this parameter is temporarily not supported, we will support it as soon as possible, thanks.

**Comment by meidli** [comment]
@zlpqingmei 
please help to complete it, here are some reference documents.

https://tools.ietf.org/html/draft-ietf-idr-segment-routing-te-policy-07#section-2.4.4
https://tools.ietf.org/html/draft-ietf-idr-segment-routing-te-policy-07#section-2.4.5
https://tools.ietf.org/html/draft-ietf-idr-segment-routing-te-policy-07#section-2.4.6
https://tools.ietf.org/html/draft-ietf-idr-tunnel-encaps-12#section-3.1
https://www.iana.org/assignments/bgp-parameters/bgp-parameters.xhtml

**Comment by xiaopeng163** [comment]
@vishchan85 could you please try the latest master branch, we did a fix for this issue in master branch.

**Comment by meidli** [comment]
@vishchan85 hi, we have finished enlp support #104 , the api document has been updated, you can continue with your test. hope for your feedback, thanks.

**Comment by vishchan85** [comment]
thanks works now
