### ISSUE TITLE
Link-bandwidth Extended Community Support Question

### ISSUE THREAD

**Issue by mnanduri** [smartbgp/yabgp#106]
Do you support link bandwidth extended community?

https://tools.ietf.org/html/draft-ietf-idr-link-bandwidth-07

**Comment by xiaopeng163** [comment]
yes, we support it https://github.com/smartbgp/yabgp/blob/master/yabgp/message/attribute/extcommunity.py#L155

**Comment by mnanduri** [comment]
Thanks for the quick reply. I will try it out.
