### ISSUE TITLE
Consider replacing netaddr dependency with ipaddress

### ISSUE THREAD

**Issue by petedaws** [smartbgp/yabgp#33]
I was wondering if you have considered removing the dependency on netaddr and moving to ipaddress which is included with python3 and has been backported to python2.

**Comment by xiaopeng163** [comment]
@petedaws that's a good idea, could you please make a pull request for that?

**Comment by petedaws** [comment]
I can get started on it. Wanted to make sure there wasn't some good reason
for sticking with netaddr.

**Comment by xiaopeng163** [comment]
Thanks a lot.

:) actually no. when I started this project I want to find a module to process IP address and network,
and I came across OpenStack neutron at that time and found `netaddr` https://github.com/openstack/neutron/blob/master/requirements.txt#L16

Now, I also think ipaddress is a good choice.

**Comment by petedaws** [comment]
Looked into this. I think it should be shelved for the time being.

There are a lot of inconsistencies between the behaviour of ipaddress
between Python2 and Python3 (mainly unicode handling) that is leading to
messy code and a lot of side-affects that I didn't anticipate.

Also, ipaddress doesn't do any Layer2 handling like netaddr does with
netaddr.EUI() so they are not functionally equivalent which leads to more
messiness.

**Comment by xiaopeng163** [comment]
close, we will consider this option in project libbgp https://github.com/smartbgp/libbgp thanks
