### ISSUE TITLE
都是洋文，谁给同胞安利一下原理？

### ISSUE THREAD

**Issue by Just2co** [smartbgp/yabgp#38]
我最近对原理性的东西很感兴趣，哪位大大给我安利一下这个项目的原理，以及使用方法？

**Comment by xiaopeng163** [comment]
我们稍后更新一个中文的readme吧，谢谢关注

**Comment by xiaopeng163** [comment]
https://github.com/smartbgp/yabgp/blob/master/README-zh.rst  请参考中文readme，thanks

**Comment by Just2co** [comment]
@xiaopeng163 看懂了，这是个连接高级路由设备通过BGP协议的软件，这个可以用来干嘛？学习CCNP还是？

**Comment by xiaopeng163** [comment]
当然不是。主要是监控和控制

**Comment by Just2co** [comment]
@xiaopeng163 监控和控制什么东东？装到自己的电脑，有哪些好处？

**Comment by xiaopeng163** [comment]
这不是个人电脑用的软件，还是建议您多看看网络知识先，CCNP，CCIE的先学习着，这个issue我就先关了。
