### ISSUE TITLE
st-te bgp policy update

### ISSUE THREAD

**Issue by cpmarvin** [smartbgp/yabgp#49]
Hi, 

I'm getting an invalid attribute list 
.... NOTIFICATION sent to 10.97.97.2 (Internal AS xxxx): code 3 (Update Message Error) subcode 1 (invalid attribute list), Data:  **c0 17 34 00 0f 00**

![image](https://user-images.githubusercontent.com/20742720/31049470-9e6f3d9a-a62b-11e7-9a3c-e16c12df9978.png)

I'm using the following post , just as an example ... but this happens if i use type 1 only.
```json
 {
    "attr": {
	    "1": 0,
	    "2": [[2, []]],
	    "3": "10.99.99.2",
	    "5": 200,
        "8": ["NO_ADVERTISE"],
        "14": {
            "afi_safi": [1, 73],
            "nexthop": "192.168.5.5",
            "nlri": {
                "distinguisher": 0,
                "color": 0,
                "endpoint": "192.168.76.1"
            }
        },
        "16": [[258, "10.75.195.199:00"]],
        "23": {
            "6": 100,
            "7": 2,
            "128": [
                 {
                     "9": 10,
                     "1": [
                         {
                             "1": {
                                 "label": 2000
                             }
                         },
                         {
                             "3": {
                                 "node": "10.1.1.1",
                                 "SID": {
                                     "label": 3000,
                                     "TC": 0,
                                     "S": 0,
                                     "TTL": 255
                                 }
                             }
                         }
                     ]
                 }
             ]
        }
    }
}
```

**Comment by xiaopeng163** [comment]
Could I know what kind of router are you using?

**Comment by meidli** [comment]
@cpmarvin 
You can make the as_path vacant or add some numbers in the second list like  "2": [[2, [25000]]], and try again.

**Comment by cpmarvin** [comment]
@meidli nothing to do with as_path. Null or values , the same error. i will check with other router version to make sure it's not something related to lack of draft compliance.

**Comment by xiaopeng163** [comment]
@cpmarvin any updates?

the platform we are using for testing is IOS-XR

```
RP/0/RP0/CPU0:r7#sh ver
Fri Oct  6 14:59:45.054 UTC
 
Cisco IOS XR Software, Version 6.2.2
Copyright (c) 2013-2017 by Cisco Systems, Inc.
 
Build Information:
Built By     : ahoang
Built On     : Sun Jul  9 20:30:46 PDT 2017
Build Host   : iox-ucs-031
Workspace    : /auto/srcarchive13/production/6.2.2/xrv9k/workspace
Version      : 6.2.2
Location     : /opt/cisco/XR/packages/
 
cisco IOS-XRv 9000 () processor
System uptime is 1 week, 17 hours, 11 minutes
```

**Comment by cpmarvin** [comment]
@xiaopeng163 still not working for me . Let me try and explain below

With the following post , without tunnel enc all is ok , the route is received and accepted

```
{
    "attr": {
	    "1": 0,
	    "2": [[2, []]],
	    "3": "10.5.5.5",
	    "5": 200,
        "8": ["NO_ADVERTISE"],
        "14": {
            "afi_safi": [1, 73],
            "nexthop": "10.5.5.5",
            "nlri": {
                "distinguisher": 0,
                "color": 0,
                "endpoint": "10.5.5.5"
                    }
               },
        "16": [[779, 0]]
    }
}
```

Adding the tunnel enc 23 results in error

```
{
    "attr": {
	    "1": 0,
	    "2": [[2, []]],
	    "3": "10.5.5.5",
	    "5": 200,
        "8": ["NO_ADVERTISE"],
        "14": {
            "afi_safi": [1, 73],
            "nexthop": "10.5.5.5",
            "nlri": {
                "distinguisher": 0,
                "color": 0,
                "endpoint": "10.5.5.5"
                    }
               },
        "16": [[779, 0]],
        "23": {
            "128": [
                 {
                     "9": 10,
                     "1": [
                         {
                             "1": {
                                 "label": 2000
                             }
                         }
                     ]
                 }
             ]
        }
    }
}
```

Looking at the draft , https://tools.ietf.org/html/draft-previdi-idr-segment-routing-te-policy-07 , section 2.2 , the Tunnel Type: SR Policy 15 needs to be set. I can't see an option for this in the configuration. 

Unfortunately i don't have access to a Cisco box to test , i'm using a Juniper device.  

Are you able to test with above post.

**Comment by xiaopeng163** [comment]
@cpmarvin thanks for your information, we will work on that and find the reason asap.

**Comment by cpmarvin** [comment]
@xiaopeng163  i believe this is not a problem with yabgp but rather with the receiving side. 
I've check all the messages from yabgp and looks good. It might be that the current version i'm using don't support tunnel type 15. 
If you can check the json against xrv9k it would be great , at least i know i'm using the correct format. 

Thx.

**Comment by xiaopeng163** [comment]
@cpmarvin Yes, I will check your POST JSON in my testing env.

**Comment by xiaopeng163** [comment]
@cpmarvin we tested with your POST JSON, it worked in our environment. So the reason maybe your router's OS version.

**Comment by cpmarvin** [comment]
@xiaopeng163 Thanks for that . Closing this as it's related to receiving side rather than yabgp.
