### ISSUE TITLE
Able to send empty Segment Lists in IPv4 SR-TE updates?

### ISSUE THREAD

**Issue by deepgajjar5** [smartbgp/yabgp#69]
Hi, 

I have been using Yabgp 0.4.0 for some time for sending IPv4 SR-TE policies. I am wondering if there is a way for segment-lists to be empty in the updates?

Currently, I am using the following json parameters to advertise the label stack:

payload['attr'] = { "1": 0, "2": [[2,[10,2,3]]], "8": [ "NO_ADVERTISE"], "14": { "afi_safi": [1, 73], "nexthop": nh, "nlri": { "distinguisher": dist, "color": color, "endpoint": prefix }}, "23": { "0": "new", "12": 4200, "13": bsid, "128": [ { "9": 10, "1" : [ { "1": { "label": 900002  } } ] } ] } }

**Comment by meidli** [comment]
Hi,

Our program support for sending empty segment-lists. But the router not support that and will process the message as malformed update.
![image](https://user-images.githubusercontent.com/30134359/37252267-48f59e7e-2559-11e8-9f15-910807826f1c.png)
The json: 
{
    "attr": {
        "1": 0, 
        "2": [], 
        "3": "192.168.5.5", 
        "5": 200, 
    	"8": ["NO_ADVERTISE"],
        "14": {
            "afi_safi": [
                1, 
                73
            ], 
            "nexthop": "10.75.44.122", 
            "nlri": {
                "distinguisher": 1, 
                "color": 12, 
                "endpoint": "199.1.1.4"
            }
        },
        "23": {
        	"0": "old",
        	"6": 100,
            "7": 25102, 
            "128": []
        }
    }
}
