### ISSUE TITLE
use route advertisement python script with yabgp config file 

### ISSUE THREAD

**Issue by deepgajjar5** [smartbgp/yabgp#74]
Hi, 

I was wondering if there is a way to use the python script which I use for route-advertisements with the yabgp config file itself? I have to manually run the python script after the bgp session gets established. 

I tried setting the 'pid-file' option to point to the python script:

pid-file = '/home/deep/advertise_ipv4_routes.py'

But this does not seem to work. Am I missing something? I am looking for a way to automate the route advertisement process as soon as bgp session is established.

**Comment by deepgajjar5** [comment]
Is there any update on this one?

**Comment by xiaopeng163** [comment]
hi @deepgajjar5 yabgp could advertise prefix by himself, we must use RESTAPI to do that. and you can write some scripts to do that separately

**Comment by deepgajjar5** [comment]
Hi @xiaopeng163, yes, I have been able to advertise prefixes through RESTAPI. 

My question is: Does the config file provide an option to run the script automatically or when the Yabgp session gets established? This can eliminate the need to run the script to advertise prefixes manually after the session gets established.

**Comment by xiaopeng163** [comment]
I am sorry for that, yabgp can't do that.

**Comment by xiaopeng163** [comment]
you can try to use our handler and write your own hander, and try to do what you want to, like auto advertises routes. http://yabgp.readthedocs.io/en/latest/extension.html

**Comment by xiaopeng163** [comment]
and I will close this issue. thanks
