### ISSUE TITLE
missing tunnel encapsulation type

### ISSUE THREAD

**Issue by marceloblanes** [smartbgp/yabgp#96]
Hi,

I'm using yabgp to inject sr policy. I was able to sucessfully inject a sr policy into cisco router, but something is missing, because the show bgp does not show the sr path. maybe the Tunnel encap attribute type that should be 15 (SR policy)
 here goes my sr_policy message:

{
        "attr": {

                "1": 0,
                "2": [[2, [65000]]],
                "3": "10.121.216.208",
                "5": 200,
                "8": ["NO_ADVERTISE"],
                "14": {
                        "afi_safi": [1, 73],
                        "nexthop": "172.31.255.64",
                        "nlri": {
                                "distinguisher": 1,
                                "color": 14,
                                "endpoint": "172.31.255.64"
                        }
                },
                "16": ["route-target:172.31.255.63:01"],
                "23": {
                        "0": "old",
                        "6": 100,
                        "7": 25102,
                        "128": [ {
                                "9": 10,
                                "1": [ {
                                        "1": {
                                                "label": 24004,
                                                "TC": 0,
                                                "S": 0,
                                                "TTL": 255
                                        }
                                },
                                {
                                        "3": {
                                                "node": "172.31.255.64",
                                                "SID": {
                                                        "label": 24002,
                                                        "TC": 0,
                                                        "S": 0,
                                                        "TTL": 255
                                                }
                                        }
                                }
                        ]
                }
                ]
        }
        }
}

RP/0/RP0/CPU0:rr-9k-ios-xrv-6.3.3#sh bgp ipv4 sr-policy [1][14][172.31.255.64]/96
Wed Jan 16 11:11:28.717 BRST
BGP routing table entry for [1][14][172.31.255.64]/96
Versions:
  Process           bRIB/RIB  SendTblVer
  Speaker                 20          20
Last Modified: Jan 16 10:53:27.852 for 00:18:01
Paths: (1 available, best #1, not advertised to any peer)
  Not advertised to any peer
  Path #1: Received by speaker 0
  Not advertised to any peer
  65000
    172.31.255.64 (metric 10) from 10.121.216.208 (10.121.216.208)
      Origin IGP, localpref 200, valid, internal, best, group-best
      Received Path ID 0, Local Path ID 1, version 20
      Community: no-advertise
      Extended community: RT:172.31.255.63:1
RP/0/RP0/CPU0:rr-9k-ios-xrv-6.3.3#

Any help is welcome. Thanks!

**Comment by xiaopeng163** [comment]
@meidli Please help to check, thanks.

**Comment by meidli** [comment]
@marceloblanes hi, change your json like this and have a try

{
"attr": {

            "1": 0,
            "2": [[2, [65000]]],
            "3": "10.121.216.208",
            "5": 200,
            "8": ["NO_ADVERTISE"],
            "14": {
                    "afi_safi": [1, 73],
                    "nexthop": "172.31.255.64",
                    "nlri": {
                            "distinguisher": 1,
                            "color": 14,
                            "endpoint": "172.31.255.64"
                    }
            },
            "16": ["route-target:172.31.255.63:01"],
            "23": {
                    "0": "new",
                    "12": 100,
                    "13": 25102,
                    "128": [ {
                            "9": 10,
                            "1": [ {
                                    "1": {
                                            "label": 24004,
                                            "TC": 0,
                                            "S": 0,
                                            "TTL": 255
                                    }
                            },
                            {
                                    "3": {
                                            "node": "172.31.255.64",
                                            "SID": {
                                                    "label": 24002,
                                                    "TC": 0,
                                                    "S": 0,
                                                    "TTL": 255
                                            }
                                    }
                            }
                    ]
            }
            ]
    }
    }
}

if it still not work, could you paste the complete router debug output please? thanks.

**Comment by marceloblanes** [comment]
Hi, yes changing to "new" in sub-tlv 0 in tlv 23 worked! thanks!
